# Generated by Django 4.0.4 on 2022-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], editable=False, max_length=6),
        ),
    ]
