# Generated by Django 4.0.4 on 2022-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_transactions_datetime_alter_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='log_extract',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
