# Generated by Django 4.0.4 on 2022-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_transactions_log_extract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='log_extract',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
